name: Build & Deploy to Pages Repo

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: your-username/project-pages
          publish_branch: main
          publish_dir: ./dist  # เปลี่ยนเป็น ./build ถ้าใช้ React
